# Placeholder for ios/Podfile
# Required for a valid Flutter iOS project structure.

# CocoaPods Flutter integration
ENV['COCOAPODS_DISABLE_STATS'] = 'true'
project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}
def flutter_ пост_install(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        # dart-define related
        'DART_DEFINES_KV_PAIRS=$(DART_DEFINES_KV_PAIRS)',
        'FLUTTER_TARGET_PLATFORM_NAME=$(FLUTTER_TARGET_PLATFORM_NAME)',
      ]
    end
  end
end

# Flutter Pod
flutter_application_path = '../../../../../../tmp/flutter' # Defaulting to where we cloned it
eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  flutter_post_install(installer)
end
